FROM eclipse-temurin:19-jre-jammy

ENV MB_PLUGINS_DIR=/home/plugins/

RUN mkdir -p /home/plugins

ADD https://downloads.metabase.com/v0.52.13/metabase.jar /home/metabase.jar
ADD https://github.com/MotherDuck-Open-Source/metabase_duckdb_driver/releases/download/0.2.12-b/duckdb.metabase-driver.jar /home/plugins/duckdb.metabase-driver.jar

RUN chmod 744 /home/plugins/duckdb.metabase-driver.jar

WORKDIR /home

CMD ["java", "-jar", "metabase.jar"]
